#!/bin/bash

W=1280
H=720

CODEC=mjpeg #mpeg4
avi=$1.avi
mpg=$1.mpg

mencoder -ovc lavc \
	 -lavcopts vcodec=${CODEC} \
	 -vf scale=${W}:${H} \
	 -o ${avi} \
	 "mf://*.jpg"

#ffmpeg -aspect 16:9 \
#       -i ${avi} \
#       -y \
#       -sameq \
#       ${mpg}
